service: basic-serverless-lambda-python

provider:
    name: aws
    runtime: python3.11
    stage: dev
    region: us-east-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  ghOpenaiChatbot:
    name: ghOpenaiChatbot
    handler: main.handler
    description: A simple chatbot that uses OpenAI's GPT-3 to generate responses.
    timeout: 30 # seconds
    memorySize: 512 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"


